### ISSUE TITLE
1.55 fails in Chrome 32

### ISSUE THREAD

**Issue by wiseleo** [philc/vimium#2144]
I use PuppyLinux Tahrpup 6.0 and Chrome 32.0.1700.77 is the last available release. I can't use the newest Ubuntu Chrome build because that build crashes my X on video sites.

Vimium auto-updated itself to 1.55 and stopped working.

1.54 loaded manually works.

Loading Vimium on example.com results in 3 errors:

```
Error in response to storage.get: TypeError: Cannot read property 'normalModeKeyStateMapping' of undefined
    at new NormalMode (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:156:28)
    at installModes (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:211:18)
    at initializeOnEnabledStateKnown (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:223:7)
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:686:7
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:370:99 extensions::sendRequest:26
safeCallbackApply extensions::sendRequest:26
handleResponse

Error in response to storage.get: TypeError: Cannot read property 'vimiumCSSInChromeStorage' of undefined
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/ui_component.js:31:32
    at Object.DomUtils.documentReady (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/lib/dom_utils.js:23:18)
    at new UIComponent (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/ui_component.js:25:16)
    at Object.Vomnibar.init (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vomnibar.js:76:76)
    at Object.DomUtils.documentComplete (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/lib/dom_utils.js:46:18)
    at initializeOnEnabledStateKnown (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:227:18)
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:686:7 extensions::sendRequest:26
safeCallbackApply extensions::sendRequest:26
handleResponse

Error in response to storage.get: TypeError: Cannot read property 'vimiumSecret' of undefined
    at HTMLIFrameElement.<anonymous> (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/ui_component.js:48:43) extensions::sendRequest:26
safeCallbackApply extensions::sendRequest:26
handleResponse
```

**Comment by smblott-github** [comment]
Thanks @wiseleo.  Those error message are related to various values Vimium stores in `chrome.storage.local`.  Chrome 32 is two and a half years old!  Are Google even maintaining it?  (E.g. security updates, etc.)

I'm not sure we're committed to maintaining Vimium on such old Chrome builds.

**Comment by wiseleo** [comment]
Thanks for the pointer.

I'll work on a patch that checks for that. 1.54 works fine. :)
