### ISSUE TITLE
cake build report type error

### ISSUE THREAD

**Issue by godhelpjun** [philc/vimium#2671]
adam@ahp:~/Downloads/software/vimium$ sudo cake build
/home/adam/Downloads/software/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:147
    shortFlag = shortFlag != null ? shortFlag.match(SHORT_FLAG)[1] : void 0;
                                                               ^

TypeError: Cannot read property '1' of null
    at buildRule (/home/adam/Downloads/software/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:147:64)
    at /home/adam/Downloads/software/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:119:22
    at buildRules (/home/adam/Downloads/software/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:122:7)
    at new OptionParser (/home/adam/Downloads/software/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:27:20)
    at Object.exports.run (/home/adam/Downloads/software/vimium/node_modules/coffeescript/lib/coffeescript/cake.js:73:14)
    at Object.<anonymous> (/usr/lib/nodejs/node-v6.11.3/lib/node_modules/coffeescript/bin/cake:15:42)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

**Comment by mrmr1993** [comment]
This error doesn't seem to touch our code at all. It looks like this is an error in the coffeescript node module.

Do you get the same error with a blank `Cakefile`?

**Comment by godhelpjun** [comment]
adam@ahp:~/Downloads/software/vimium$ ll Cakefile
-rw-rw-r-- 1 adam adam 0 Sep 27 00:48 Cakefile
adam@ahp:~/Downloads/software/vimium$ cake build
No such task: build

To see a list of all tasks/options, run "cake"

**Comment by godhelpjun** [comment]
run cake with an empty cakefile,shows above.
I have had the most lated node 8.5 installed.
adam@ahp:~/Downloads/software/vimium$ type node
node is hashed (/usr/lib/nodejs/node-v8.5.0-linux-x64/bin/node)
adam@ahp:~/Downloads/software/vimium$ coffee -v
CoffeeScript version 2.0.0
Thanks.

**Comment by mrmr1993** [comment]
We don't yet support Coffeescript v2, as it's only just come out. You'll need to downgrade to the previous version.

**Comment by godhelpjun** [comment]
thanks.
adam@ahp:~/Downloads/software/vimium$ coffee -v
CoffeeScript version 1.12.7
Now,it works.Thank you very much.

**Comment by smblott-github** [comment]
This needs to be in the instructions.

**Comment by mrmr1993** [comment]
@smblott-github I'm not going to have a chance to make a PR until Friday. I'm happy to do it then, but feel free to change it sooner.

I'll try and get us up to Coffeescript v2 standard when I can, it looks like we can get some nice improvements from it going forward.

**Comment by fugounashi** [comment]
Documentation is broken. Should specify the version of coffee required.

npm install --global coffeescript@1.12.7

**Comment by philc** [comment]
Closing, as we've since moved off of coffeescript and cake.
