### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by yhuangatimvucom** [philc/vimium#3023]
I am using these command to build it:
`npm install --save-dev coffeescript
cake build`
But fail with following output
`npm WARN saveError ENOENT: no such file or directory, open '/Users/yhuang/Dropbox/myproject/git/firefox/philc/vimium/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/yhuang/Dropbox/myproject/git/firefox/philc/vimium/package.json'
npm WARN vimium No description
npm WARN vimium No repository field.
npm WARN vimium No README data
npm WARN vimium No license field.

+ coffeescript@2.3.0
updated 1 package in 0.568s
/Users/yhuang/Dropbox/myproject/git/firefox/philc/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:147
    shortFlag = shortFlag != null ? shortFlag.match(SHORT_FLAG)[1] : void 0;
                                                               ^

TypeError: Cannot read property '1' of null
    at buildRule (/Users/yhuang/Dropbox/myproject/git/firefox/philc/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:147:64)
    at /Users/yhuang/Dropbox/myproject/git/firefox/philc/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:119:22
    at buildRules (/Users/yhuang/Dropbox/myproject/git/firefox/philc/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:122:7)
    at new OptionParser (/Users/yhuang/Dropbox/myproject/git/firefox/philc/vimium/node_modules/coffeescript/lib/coffeescript/optparse.js:27:20)
    at Object.exports.run (/Users/yhuang/Dropbox/myproject/git/firefox/philc/vimium/node_modules/coffeescript/lib/coffeescript/cake.js:73:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffeescript/bin/cake:22:42)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

`

**Comment by smblott-github** [comment]
It looks like you are trying to install Vimium as an npm package, but Vimium is not an npm package.

The build instructions are [here](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#installing-from-source).

**Comment by ris58h** [comment]
@yhuangatimvucom 
@marcelpaulo 
Guys you have to install coffeescript 1 (I have coffeescript@1.12.7) globally to make it work.

@smblott-github 
Why don't we use any dependency management to build Vimium? I believe that install packages globally (and manually) is a bad practice.

**Comment by smblott-github** [comment]
> Why don't we use any dependency management to build Vimium?

No reason, I think.  Just nobody's done it.

**Comment by ris58h** [comment]
@smblott-github I've opened https://github.com/philc/vimium/issues/2869 some time ago but didn't get any response. Shall I make PR?

**Comment by smblott-github** [comment]
@ris58h... Sure.

However, when we `cake build`, the local version of `cake` and `coffee` is unlikely to be on the users `$PATH`.  Is there an easy way around that?

**Comment by yhuangatimvucom** [comment]
> Guys you have to install coffeescript 1 (I have coffeescript@1.12.7) globally to make it work.
@ris58h How to ? 
I am in mac, the command I used is "npm install --global coffeescript"

**Comment by ris58h** [comment]
@yhuangatimvucom `npm i -g coffeescript@1.12.7`

**Comment by marcelpaulo** [comment]
> npm i -g coffeescript@1.12.7

Good one ! I didn't know you could specify the version when installing. I was using `npm install coffeescript` and it installed the latest version, **2.3.0**.
