### ISSUE TITLE
Vomnibar does not list suggestions when triggered with o/O

### ISSUE THREAD

**Issue by mimkorn** [philc/vimium#3656]
When I use B,b, or T, suggestions are brought up correctly. Using o/O does not show anything as I type to vomnibar. 

Vimium is 1.66

Brave	1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
Revision	d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS	macOS Version 10.15.6 (Build 19G73)
JavaScript	V8 8.4.371.23
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=PrefetchPrivacyChanges,AutoupgradeMixedContent,PassiveMixedContentWarning,DnsOverHttps,MixedContentSiteSetting,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity --disable-features=TextFragmentAnchor,NotificationTriggers,AutofillServerCommunication,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,VideoPlaybackQuality,UseButtonTranslateBubbleUI,TabHoverCards,SmsReceiver,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser

**Comment by mvtango** [comment]
I have the same problem with vimium 1.66, Firefox 80.0.1 on Debian Buster. 

It does not happen in Firefox 79 or Firefox 80.0.

**Comment by Mishkun** [comment]
Same thing on Yandex Browser, but also T command doesn't work for me.

Got this in JS console
```
vomnibar.js:281 Uncaught TypeError: Cannot read property 'customSearchMode' of undefined
    at VomnibarUI.onInput (vomnibar.js:281)
    at HTMLInputElement.<anonymous> (vomnibar.js:4)
```

**Comment by gdh1995** [comment]
@Mishkun Which version of Vimium are you using? The web store version (v1.66) or the master version from GitHub?

**Comment by Mishkun** [comment]
@gdh1995 I use web store 1.66 version

**Comment by Mishkun** [comment]
@gdh1995 
Got this
```
Uncaught TypeError: Cannot read property 'customSearchMode' of undefined
    at VomnibarUI.onInput (vomnibar.js:292)
```
on current master

**Comment by gdh1995** [comment]
The background process may also has an error, please open `chrome://extensions/?id=dbepggeogbaibhgnhhndojpepiihcmeb`, turn on `Developer Tools` and click the "Background page" link to see its console.

**Comment by Mishkun** [comment]
@gdh1995 Got this

```
Error handling response: TypeError: Cannot read property 'split' of undefined
    at Object.decodeURIByParts (chrome-extension://mkijefhkedlplfoodejafiancpfmapkc/lib/utils.js:102:16)
    at Suggestion.shortenUrl (chrome-extension://mkijefhkedlplfoodejafiancpfmapkc/background_scripts/completion.js:181:22)
    at MultiCompleter.prepareSuggestions (chrome-extension://mkijefhkedlplfoodejafiancpfmapkc/background_scripts/completion.js:805:21)
    at chrome-extension://mkijefhkedlplfoodejafiancpfmapkc/background_scripts/completion.js:762:28
    at chrome-extension://mkijefhkedlplfoodejafiancpfmapkc/lib/utils.js:396:44
    at chrome-extension://mkijefhkedlplfoodejafiancpfmapkc/lib/utils.js:418:52
    at chrome-extension://mkijefhkedlplfoodejafiancpfmapkc/background_scripts/completion.js:746:11
    at chrome-extension://mkijefhkedlplfoodejafiancpfmapkc/background_scripts/completion.js:481:7
```

**Comment by caminsha** [comment]
I have the same issue in Firefox.
The following things are my system details:
Version OS: Fedora 33
Version browser: 90.0.2 (64-bit)
Version vimium: 1.67
Installed by: Firefox add-on store

Normally the extension shows me all different things when using the command `o` or `O` like opened tabs, bookmarks and history but at the moment it doesn't work the way as expected.

When I close the browser and restart it again everything's ok but that's pretty annoying for me as I delete all browser data (except bookmarks) when closing the browser.

Unfortunately I didn't see any log outputs from vimium in firefox's developer console. If you'd tell me how to give you more information I'd like to share them, for sure.
