### ISSUE TITLE
press f in the Gmail not work

### ISSUE THREAD

**Issue by zyf0330** [philc/vimium#4126]
**Describe the bug**
Press f in the Gmail doesn't work. The open link bar at the right-bottom corner blinks and disappear quickly.

**To Reproduce**
1. Go to URL  'https://mail.google.com/mail/u/0/#inbox'
2. Click on 'f'

**Browser and Vimium version**

Chrome: Version 105.0.5195.125 (Official Build) (64-bit)
Vimium: 1.67

This is error stack shown in the devtool console:
```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'add')
    at FilterHints.getMatchingHints (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/link_hints.js:731:39)
    at FilterHints.fillInMarkers (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/link_hints.js:711:17)
    at new LinkHintsMode (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/link_hints.js:282:24)
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/link_hints.js:178:28
    at Object.onLoaded (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/lib/settings.js:82:14)
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/link_hints.js:171:59
    at DomUtils.documentReady (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/lib/dom_utils.js:20:16)
    at Object.activateMode (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/link_hints.js:171:21)
    at linkHintsMessage (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:269:48)
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/content_scripts/vimium_frontend.js:305:7
```

**Comment by CaedenPH** [comment]
duplicate of #2466

**Comment by zyf0330** [comment]
No, it's not. But at now the problem is gone.
